### ISSUE TITLE
Create a simple map in a json file

### ISSUE THREAD

**Issue by havok13888** [havok13888/Master-Game#15]

**Comment by havok13888** [comment]
https://jsoneditoronline.org/

You can use this to make the file and then save it.

Maps should be stored under Master-Game/Assets/Maps/<filename>.json

**Comment by wilsont3** [comment]
It would be fun if everyone could create a map so that we have multiple maps to create.  Store your maps in a file that ends in ".json".

**Comment by wilsont3** [comment]
For now, the max size of the map is 10x10, but feel free to make it simpler too.

**Comment by jamiahuswalton** [comment]
I created a 4 X 4 map for now. 

I think that we should look into changing the way we store the map in code. In other words, I think that we should use List instead of an array. I ran into an issue with dynamically creating arrays. Maybe there was something I was doing that was wrong.  I made a pull request. 

#18
